Entity/Comment.php
<?php

namespace Eab\CommentBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use FOS\CommentBundle\Entity\Comment as BaseComment;
use FOS\CommentBundle\Model\SignedCommentInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity
 * @ORM\ChangeTrackingPolicy("DEFERRED_EXPLICIT")
 */
class Comment extends BaseComment implements SignedCommentInterface
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * Thread of this comment
     *
     * @var Thread
     * @ORM\ManyToOne(targetEntity="Eab\CommentBundle\Entity\Thread")
     */
    protected $thread;

    /**
     * Author of the comment, NULL means anonymous
     *
     * @var string $author
     * @ORM\Column(type="string", nullable=true)
     */
    protected $author;

    /**
     * Set the author to the current eZ Publish user's login
     * @var UserInterface $author
     */
    public function setAuthor(UserInterface $author)
    {
        /* It would be more efficient to have join to a User entity, store the ID
         * and the user's real name (or alias) in the table. Currently to look up
         * each user's real name (or alias) requires first running a query for
         * each author in getAuthorName() ie 2 queries rather than 1.
         * Also, using the service container from an entity is regarded as
         * bad practice.
         */
        // Something like $author->getAPIUser()->content->fields['first_name'] should work
        // or maybe content->getFieldValue( 'first_name' )
        $login = $author->getAPIUser()->login;
        //$id = $author->getAPIUser()->id;
        //$roles = $author->getRoles();
        $this->author = $login;
    }

    public function getAuthor()
    {
        if ( $this->author == "anonymous" ) {
            return null;
        }
        return $this->author;
    }

    public function getAuthorName()
    {
        $author = $this->getAuthor();
        if ( null === $author or "anonymous" == $author ) {
            return 'Anonymous';
        }
        return $author;
    }
}

Entity/Thread.php
<?php

namespace Eab\CommentBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use FOS\CommentBundle\Entity\Thread as BaseThread;

/**
 * @ORM\Entity
 * @ORM\ChangeTrackingPolicy("DEFERRED_EXPLICIT")
 */
class Thread extends BaseThread
{
    /**
     * @var string $id
     *
     * @ORM\Id
     * @ORM\Column(type="string")
     */
    protected $id;

}

Resources/views/Thread/comment.html.twig
{# Rather than override and copy all of FOSCommentBundle:Thread:comment_content.html.twig we can
override this small template and one block of comment_content.html.twig #}

{% set view = view|default('tree') %}
{% set depth = depth|default(0) %}

{% embed "FOSCommentBundle:Thread:comment_content.html.twig" %}

    {% block fos_comment_comment_metas_authorline %}
        {% trans from 'FOSCommentBundle' %}fos_comment_comment_show_by{% endtrans %}
        <span class="fos_comment_comment_authorname">
            {% if comment is fos_comment_in_state(constant( 'FOS\\CommentBundle\\Model\\CommentInterface::STATE_DELETED' )) %}
                {% trans from 'FOSCommentBundle' %}fos_comment_comment_deleted{% endtrans %}
            {% else %}
                {{ screenname( comment.authorName ) }}
            {% endif %}
        </span> - <span class="timeago" title="{{ comment.createdAt|date( 'c' ) }}">{{ comment.createdAt|date }}</span>
    {% endblock fos_comment_comment_metas_authorline %}

{% endembed %}

Resources/views/Thread/comment_edit.html.twig
{#
Modified version of FOSCommentBundle template. For eZ Publish the form token is
'ezxform_token' not '_token'.
#}

<div class="fos_comment_comment_form_holder">
    <form class="fos_comment_comment_edit_form" action="{{ url('fos_comment_put_thread_comments', {'id': comment.thread.id, 'commentId': comment.id}) }}" method="POST">

        {% block fos_comment_form_fields %}
            {{ form_errors(form) }}
            {{ form_errors(form.body) }}
            {{ form_widget(form.body) }}

            {# eZ Publish requires ezxform_token not _token #}
            {{ form_widget(form.ezxform_token) }}
        {% endblock %}

        <div class="fos_comment_submit">
            <button type="button" class="fos_comment_comment_edit_cancel">{% trans from 'FOSCommentBundle' %}fos_comment_comment_edit_cancel{% endtrans %}</button>
            {% block fos_comment_form_submit %}
                <input type="submit" value="{% trans from 'FOSCommentBundle' %}fos_comment_comment_edit_submit{% endtrans %}" />
            {% endblock %}
        </div>

        <input type="hidden" name="_method" value="PUT">

    </form>
</div>

Resources/views/Thread/comment_new.html.twig
{# Override template to modify FOSCommentBundle's new comment title #}

{% embed "FOSCommentBundle:Thread:comment_new_content.html.twig" %}

    {% block fos_comment_form_title %}
            {% if first %}
                <h3>{% trans from 'FOSCommentBundle' %}fos_comment_comment_new_headline_first{% endtrans %}</h3>
            {% elseif parent is not null %}
                <h3>{% trans with {"%name%": screenname( parent.authorName ) } from 'FOSCommentBundle' %}fos_comment_comment_reply_reply_to{% endtrans %}</h3>
            {% else %}
                <h3>{% trans from 'FOSCommentBundle' %}fos_comment_comment_new_headline{% endtrans %}</h3>
            {% endif %}
    {% endblock %}

{% endembed %}

Resources/views/Thread/comments-notimeago-example.html.twig
{# Master template for comments, overriding FOS\CommentBundle/Resources/views/Thread/Comments.html.twig #}

{% set depth = depth|default(0) %}
{% set view = view|default('tree') %}

{% if depth == 0 %}
    {% if fos_comment_can_comment_thread(thread) %}
        {% render url("fos_comment_new_thread_comments", {"id": thread.id}) %}
    {% endif %}

    {% if fos_comment_can_edit_thread(thread) %}
    <div class="fos_comment_thread_commentable">
        <button data-url="{{ url('fos_comment_edit_thread_commentable', {'id': thread.id, 'value': not thread.commentable}) }}" class="fos_comment_thread_commentable_action">
            {{ (thread.commentable ? 'fos_comment_thread_close' : 'fos_comment_thread_open') | trans({}, 'FOSCommentBundle') }}
        </button>
    </div>
    {% else %}
        You need to login to add a comment
    {% endif %}

    {% set count = thread.numComments %}
    <h3>{% transchoice count with {'%count%': count} from "FOSCommentBundle" %}fos_comment_thread_comment_count{% endtranschoice %}</h3>
{% endif %}

{% for commentinfo in comments %}
    {% include "FOSCommentBundle:Thread:comment.html.twig" with { "children": commentinfo.children, "comment": commentinfo.comment, "depth": depth, "view": view } %}
{% endfor %}

Resources/views/Thread/comments.html.twig
{# Overriding FOS\CommentBundle/Resources/views/Thread/comments.html.twig #}

{% set depth = depth|default(0) %}
{% set view = view|default('tree') %}

{% if depth == 0 %}
    {% if fos_comment_can_comment_thread(thread) %}
        {% render url("fos_comment_new_thread_comments", {"id": thread.id}) %}
    {% else %}
        {% block fos_comment_please_login %}
        <div class="please-login">
            You need to <a href="#login">login</a> (<a href="/user/register">register</a> first) to add a comment
        </div>
        {% endblock %}
    {% endif %}

    {% if fos_comment_can_edit_thread(thread) %}
    <div class="fos_comment_thread_commentable">
        <button data-url="{{ url('fos_comment_edit_thread_commentable', {'id': thread.id, 'value': not thread.commentable}) }}" class="fos_comment_thread_commentable_action">
            {{ (thread.commentable ? 'fos_comment_thread_close' : 'fos_comment_thread_open') | trans({}, 'FOSCommentBundle') }}
        </button>
    </div>
    {% endif %}

    <script type="text/javascript">
        {# Add relative timestamps to comments. See EabCommentBundle/Resources/doc/Timeago.md #}
        {# Other useful events include: fos_comment_removing_comment fos_comment_edit_comment
           but they are not useful for updating timestamps #}
        $(document).on( 'fos_comment_new_comment fos_comment_add_comment', function(event, data) {
            $( "span.timeago" ).timeago();
        });
        $(document).ready( function() {
            $( "span.timeago" ).timeago();
        });
    </script>

{% endif %}

{% for commentinfo in comments %}
    {% include "FOSCommentBundle:Thread:comment.html.twig" with { "children": commentinfo.children, "comment": commentinfo.comment, "depth": depth, "view": view } %}
{% endfor %}